import{a as m,S as L,i as M}from"./assets/vendor-b725de7c.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const t={form:document.querySelector(".search-form"),input:document.querySelector(".search-inp"),searchBtn:document.querySelector(".search-btn"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-btn"),loader:document.querySelector(".loader-container")};m.defaults.baseURL="https://pixabay.com/api";const v="42030436-f44bf17f2fc4b636ae2b8b7a9",n="is-hidden";let c=1,u="",y=0;const q=new L(".gallery-item a",{captionsData:"alt",captionDelay:250});t.form.addEventListener("submit",w);async function w(r){if(r.preventDefault(),t.gallery.innerHTML="",c=1,t.loadMoreBtn.classList.add(n),u=t.form.query.value.trim(),!u){f("The search field can't be empty! Please, enter your request!");return}try{const{hits:o,totalHits:a}=await p(u);y=Math.ceil(a/15),h(o,t.gallery),o.length>0?(t.loadMoreBtn.classList.remove(n),t.loadMoreBtn.addEventListener("click",S)):(t.loadMoreBtn.classList.add(n),f("Sorry, there are no images matching your search query. Please, try again!")),i(!1)}catch(o){console.log(o)}finally{t.form.reset(),c===y&&(t.loadMoreBtn.classList.add(n),f("We're sorry, but you've reached the end of search results!"))}}async function S(){c+=1;try{i(!0),t.loadMoreBtn.classList.add(n);const{hits:r}=await p(u,c);h(r,t.gallery),i(!1),B(),t.loadMoreBtn.classList.remove(n)}catch(r){console.log(r)}finally{c===y&&(t.loadMoreBtn.classList.add(n),f("We're sorry, but you've reached the end of search results!"))}}async function p(r,o=1){i(!0);try{return(await m.get("/",{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}catch(a){throw console.error(a),a}finally{i(!1)}}function h(r){const o=r.map(({webformatURL:a,largeImageURL:d,tags:e,likes:s,views:l,comments:g,downloads:b})=>`
          <li class="gallery-item">
    <a class="gallery-link" href="${d}">
      <img
        class="gallery-image"
        src="${a}"
        alt="${e}"
      />
      <p class="gallery-descr">likes: <span class="descr-span">${s}</span> views: <span class="descr-span">${l}</span> comments: <span class="descr-span">${g}</span> downloads: <span class="descr-span">${b}</span></p>
    </a>
  </li>`).join("");t.gallery.insertAdjacentHTML("beforeend",o),q.refresh()}function f(r){M.show({class:"error-svg",position:"topRight",icon:"error-svg",message:r,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function i(r=!0){t.loader.style.display=r?"inline-block":"none"}function B(){const r=document.querySelector(".gallery-link").getBoundingClientRect();window.scrollBy({top:r.height*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
